### ISSUE TITLE
Lua script error with summon

### ISSUE THREAD

**Issue by whitecrixu** [opentibiabr/otservbr-global-archived#1345]
Players is can't log in
Napinacz has logged in.
Lua Script Error: [CreatureScript Interface] 
data/creaturescripts/scripts/others/summon.lua:onLogin
data/creaturescripts/scripts/others/summon.lua:29: attempt to index global 'summonpet' (a nil value)
stack traceback:
        [C]: in function '__index'
        data/creaturescripts/scripts/others/summon.lua:29: in function <data/creaturescripts/scripts/others/summon.lua:10>
Napinacz has logged out.
System: Ubuntu 18.04LTS

**Comment by MajestyOTBR** [comment]
Why you copied the error and pasted on issue title? Why you didn't followed the issue template? 

Make sure you are using updated repository and nex time create a decent issue here.

**Comment by majestyotbr** [comment]
Why you copied the error and pasted on issue title? Why you didn't followed the issue template?

Make sure you are using updated repository and next time create a decent issue here.

**Comment by whitecrixu** [comment]
i using update repo and sorry ;)

**Comment by majestyotbr** [comment]
So, explain better in the issue, not only with copy & paste of error.

**Comment by whitecrixu** [comment]
Problem is some players i get error in terminal and player lighting in vip list on white and he can't log in after I change in DB all login time date and he can log.

**Comment by majestyotbr** [comment]
I think the problem was fixed in this commit:
https://github.com/opentibiabr/otservbr-global/commit/59877af4d2ca37e19e3b38ffad12e654c8fd08b9

**Comment by whitecrixu** [comment]
Ok try. Thank You.

**Comment by whitecrixu** [comment]
still not work
error is about

`   if not c then return false end`
`       player:sendCancelMessage("You can't have other summons.")`

**Comment by thatmichaelguy** [comment]
data/creaturescripts/scripts/others/summon.lua
Comment out Line 29 & 30
``-- local deltaSpeed = math.max(player:getBaseSpeed() - summonpet:getBaseSpeed(), 0)``
``-- summonpet:changeSpeed(deltaSpeed)``

Looks like it was broken a few commits ago, i think 'summonpet:' is meant to be 'summonMonster:' but I'm not sure and haven't tried it.

**Comment by whitecrixu** [comment]
I change for that now and not see problem.
[https://github.com/mattyx14/otxserver/blob/otxserv4/data/creaturescripts/scripts/pet.lua](url)
